ALTER TABLE clinic_appointments
    ADD COLUMN IF NOT EXISTS start_time TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS end_time TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS patient_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS state VARCHAR(32) NOT NULL DEFAULT 'PENDING';

ALTER TABLE clinic_appointments
    ALTER COLUMN patient_name SET NOT NULL;